INSERT INTO TB_BOARD_TYPE(BOARD_TYPE_SEQ, BOARD_TYPE_CODE, BOARD_TYPE_NM) VALUES ('1', 'normal', '일반')
INSERT INTO TB_BOARD_TYPE(BOARD_TYPE_SEQ, BOARD_TYPE_CODE, BOARD_TYPE_NM) VALUES ('2', 'qa', '질문')
INSERT INTO TB_BOARD_TYPE(BOARD_TYPE_SEQ, BOARD_TYPE_CODE, BOARD_TYPE_NM) VALUES ('3', 'pr', '홍보')